## Ejemplo Feed Forward con 3 hidden layers

<img src="img/fp4.png" />

In [1]:
import numpy as np

# funcion Sigmoid
def sig(x):
    return 1.0 / (1.0 + np.exp(-x))

# Entradas y pesos:
x = np.array([[0.9,0.1, 0.8]]).T
wa = np.array([[0.9,0.3,0.4],[0.2, 0.8, 0.2],[0.1,0.5,0.6]])

# output layer2
oL2 = sig(np.dot(wa,x))

# saLIDA
print("Salida Layer 2:")
print(oL2)

Salida Layer 2:
[[0.76133271]
 [0.60348325]
 [0.65021855]]


In [2]:
wb = np.array([[0.3,0.7,0.5],[0.6, 0.5, 0.2],[0.8,0.1,0.9]])

# output layer3
output = sig(np.dot(wb,oL2))
 
print(output)

[[0.72630335]
 [0.70859807]
 [0.77809706]]


## One Step:

In [3]:
# datos de entrada
x = np.array([[0.9,0.1, 0.8]]).T

# pesos w
wa = np.array([[0.9,0.3,0.4],[0.2, 0.8, 0.2],[0.1,0.5,0.6]])
wb = np.array([[0.3,0.7,0.5],[0.6, 0.5, 0.2],[0.8,0.1,0.9]])

# feed forward
o = sig(np.dot(wb,sig(np.dot(wa,x)))) 

# imprimir salida
print(output)

[[0.72630335]
 [0.70859807]
 [0.77809706]]
