## Funciones Basicas de Tensorflow 2.x para NLP

In [3]:
import warnings
warnings.filterwarnings('ignore')

import keras 
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import pandas as pd
import tensorflow as tf
from tensorflow import keras

# Este notebook require Tensorflow 2.X

### Generacion de cadenas de largo 5.

El siguiente codigo utiliza las funcionalidaders de Tensorflow 2.x para dividir una secuencia de 0 a 14 en ventanas de tamano 5. Despues de partir la sequencia en las ventanas, las baraja y luego las separa en batches de X y Y.

In [29]:
np.random.seed(42)
tf.random.set_seed(42)
n_steps = 5

# carga la colleccion en tensor slices
dataset = tf.data.Dataset.from_tensor_slices(tf.range(15)) 
# genera las series de tamano 5 con shift de 2
dataset = dataset.window(n_steps, shift=2, drop_remainder=True)
# genera las cadenas individuales.
dataset = dataset.flat_map(lambda window: window.batch(n_steps))

for item in enumerate(dataset):
  print(item[1].numpy())

[0 1 2 3 4]
[2 3 4 5 6]
[4 5 6 7 8]
[ 6  7  8  9 10]
[ 8  9 10 11 12]
[10 11 12 13 14]


In [30]:
# Baraja el dataset y lo separa en 2 ventanas
dataset = dataset.shuffle(10).map(lambda window: (window[:-1], window[1:]))
# crea batches de 3 elementos
dataset = dataset.batch(3).prefetch(1)

for item, (X,Y) in enumerate(dataset):
  print("**** Batch:",item," ****")
  print("== X ==")
  print(X.numpy())
  print("== Y ==")
  print(Y.numpy())

**** Batch: 0  ****
== X ==
[[0 1 2 3]
 [2 3 4 5]
 [4 5 6 7]]
== Y ==
[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 8]]
**** Batch: 1  ****
== X ==
[[ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]
== Y ==
[[ 7  8  9 10]
 [ 9 10 11 12]
 [11 12 13 14]]
